apiVersion: v1
kind: Service
metadata:
  name: {{ include "awesome-api-a.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "awesome-api-a.name" . }}
    helm.sh/chart: {{ include "awesome-api-a.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.awesomeApiA.service.type }}
  ports:
    - port: {{ .Values.awesomeApiA.service.port }}
      targetPort: {{ .Values.awesomeApiA.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "awesome-api-a.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}