{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "awesome-api-a.name" . -}}
{{- $servicePort := .Values.awesomeApiA.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "awesome-api-a.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "awesome-api-a.name" . }}
    helm.sh/chart: {{ include "awesome-api-a.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: "awesome-api-a.{{ .Values.global.kubeClusterHostname }}"
    http:
      paths:
        - backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
{{- end }}
