# Default values for awesome-api-a.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global Values
global:
  awesome-service-b: awesome-app-b
  kubeClusterHostname: kube-cluster-1.awesome-corp.com
  rabbitMqHost: "rabbitmq-awesome-host"
  rabbitMqPass: ""
  rabbitMqPort: "5672"

image:
  pullPolicy: IfNotPresent

# Awesome API A
awesomeApiA:
  image:
    repository: quay.io/awesome-api-a
    tag: 3.2.0
  replicaCount: 3
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Config Variables
  backendFooServiceHostname: foo-backed-service
  logLevel: info
  port: 8080
  rabbitMqQueueName: awesomeness
  rabbitMqUser: awesome.user1

# Ingress for the service
ingress:
  enabled: true
  defaultBackend:
    enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
